// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: tracert_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TracertServiceClient is the client API for TracertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TracertServiceClient interface {
	Login(ctx context.Context, in *LoginInput, opts ...grpc.CallOption) (*User, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*StringMessage, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*StringMessage, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*StringMessage, error)
	QuestionList(ctx context.Context, in *QuestionGroupListInput, opts ...grpc.CallOption) (*QuestionGroupList, error)
	AlumniRegistration(ctx context.Context, in *AlumniRegistrationInput, opts ...grpc.CallOption) (*AlumniRegistrationInput, error)
	CertificateCreate(ctx context.Context, in *Certificate, opts ...grpc.CallOption) (*Certificate, error)
	AlumniCreate(ctx context.Context, in *Alumni, opts ...grpc.CallOption) (*Alumni, error)
	AlumniList(ctx context.Context, in *ListInput, opts ...grpc.CallOption) (TracertService_AlumniListClient, error)
	AlumniGet(ctx context.Context, in *Alumni, opts ...grpc.CallOption) (*Alumni, error)
	AlumniAppraiserCreate(ctx context.Context, in *AlumniAppraiser, opts ...grpc.CallOption) (*AlumniAppraiser, error)
	AlumniAppraiserList(ctx context.Context, in *ListInput, opts ...grpc.CallOption) (TracertService_AlumniAppraiserListClient, error)
	AlumniAppraiserGet(ctx context.Context, in *AlumniAppraiser, opts ...grpc.CallOption) (*AlumniAppraiser, error)
	// rpc AlumniAppraiserUpdate(AlumniAppraiser) returns (AlumniAppraiser) {}
	UserCreate(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	UserList(ctx context.Context, in *ListInput, opts ...grpc.CallOption) (TracertService_UserListClient, error)
	UserGet(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	LegalizeCheck(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*Legalize, error)
	LegalizeUpload(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error)
	LegalizeList(ctx context.Context, in *ListInput, opts ...grpc.CallOption) (TracertService_LegalizeListClient, error)
	LegalizeGet(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error)
	LegalizeGetOwn(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*Certificates, error)
	LegalizeDone(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error)
	LegalizeVerified(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*Legalize, error)
	LegalizeRejected(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error)
	LegalizeApproved(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*Legalize, error)
	LegalizeRating(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*StringMessage, error)
	LegalizeExtended(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error)
	UserAnswerCreate(ctx context.Context, in *UserAnswer, opts ...grpc.CallOption) (*UserAnswer, error)
	TracerCreate(ctx context.Context, in *Tracer, opts ...grpc.CallOption) (*Tracer, error)
	GetTrace(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*TracerList, error)
	GetLastTrace(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*Tracer, error)
	GetMyAnswers(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*UserAnswerList, error)
}

type tracertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTracertServiceClient(cc grpc.ClientConnInterface) TracertServiceClient {
	return &tracertServiceClient{cc}
}

func (c *tracertServiceClient) Login(ctx context.Context, in *LoginInput, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.TracertService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/proto.TracertService/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/proto.TracertService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/proto.TracertService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) QuestionList(ctx context.Context, in *QuestionGroupListInput, opts ...grpc.CallOption) (*QuestionGroupList, error) {
	out := new(QuestionGroupList)
	err := c.cc.Invoke(ctx, "/proto.TracertService/QuestionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) AlumniRegistration(ctx context.Context, in *AlumniRegistrationInput, opts ...grpc.CallOption) (*AlumniRegistrationInput, error) {
	out := new(AlumniRegistrationInput)
	err := c.cc.Invoke(ctx, "/proto.TracertService/AlumniRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) CertificateCreate(ctx context.Context, in *Certificate, opts ...grpc.CallOption) (*Certificate, error) {
	out := new(Certificate)
	err := c.cc.Invoke(ctx, "/proto.TracertService/CertificateCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) AlumniCreate(ctx context.Context, in *Alumni, opts ...grpc.CallOption) (*Alumni, error) {
	out := new(Alumni)
	err := c.cc.Invoke(ctx, "/proto.TracertService/AlumniCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) AlumniList(ctx context.Context, in *ListInput, opts ...grpc.CallOption) (TracertService_AlumniListClient, error) {
	stream, err := c.cc.NewStream(ctx, &TracertService_ServiceDesc.Streams[0], "/proto.TracertService/AlumniList", opts...)
	if err != nil {
		return nil, err
	}
	x := &tracertServiceAlumniListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TracertService_AlumniListClient interface {
	Recv() (*AlumniListResponse, error)
	grpc.ClientStream
}

type tracertServiceAlumniListClient struct {
	grpc.ClientStream
}

func (x *tracertServiceAlumniListClient) Recv() (*AlumniListResponse, error) {
	m := new(AlumniListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tracertServiceClient) AlumniGet(ctx context.Context, in *Alumni, opts ...grpc.CallOption) (*Alumni, error) {
	out := new(Alumni)
	err := c.cc.Invoke(ctx, "/proto.TracertService/AlumniGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) AlumniAppraiserCreate(ctx context.Context, in *AlumniAppraiser, opts ...grpc.CallOption) (*AlumniAppraiser, error) {
	out := new(AlumniAppraiser)
	err := c.cc.Invoke(ctx, "/proto.TracertService/AlumniAppraiserCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) AlumniAppraiserList(ctx context.Context, in *ListInput, opts ...grpc.CallOption) (TracertService_AlumniAppraiserListClient, error) {
	stream, err := c.cc.NewStream(ctx, &TracertService_ServiceDesc.Streams[1], "/proto.TracertService/AlumniAppraiserList", opts...)
	if err != nil {
		return nil, err
	}
	x := &tracertServiceAlumniAppraiserListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TracertService_AlumniAppraiserListClient interface {
	Recv() (*AlumniAppraiserListResponse, error)
	grpc.ClientStream
}

type tracertServiceAlumniAppraiserListClient struct {
	grpc.ClientStream
}

func (x *tracertServiceAlumniAppraiserListClient) Recv() (*AlumniAppraiserListResponse, error) {
	m := new(AlumniAppraiserListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tracertServiceClient) AlumniAppraiserGet(ctx context.Context, in *AlumniAppraiser, opts ...grpc.CallOption) (*AlumniAppraiser, error) {
	out := new(AlumniAppraiser)
	err := c.cc.Invoke(ctx, "/proto.TracertService/AlumniAppraiserGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) UserCreate(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.TracertService/UserCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) UserList(ctx context.Context, in *ListInput, opts ...grpc.CallOption) (TracertService_UserListClient, error) {
	stream, err := c.cc.NewStream(ctx, &TracertService_ServiceDesc.Streams[2], "/proto.TracertService/UserList", opts...)
	if err != nil {
		return nil, err
	}
	x := &tracertServiceUserListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TracertService_UserListClient interface {
	Recv() (*UserListResponse, error)
	grpc.ClientStream
}

type tracertServiceUserListClient struct {
	grpc.ClientStream
}

func (x *tracertServiceUserListClient) Recv() (*UserListResponse, error) {
	m := new(UserListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tracertServiceClient) UserGet(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.TracertService/UserGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeCheck(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*Legalize, error) {
	out := new(Legalize)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeUpload(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error) {
	out := new(Legalize)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeList(ctx context.Context, in *ListInput, opts ...grpc.CallOption) (TracertService_LegalizeListClient, error) {
	stream, err := c.cc.NewStream(ctx, &TracertService_ServiceDesc.Streams[3], "/proto.TracertService/LegalizeList", opts...)
	if err != nil {
		return nil, err
	}
	x := &tracertServiceLegalizeListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TracertService_LegalizeListClient interface {
	Recv() (*LegalizeListResponse, error)
	grpc.ClientStream
}

type tracertServiceLegalizeListClient struct {
	grpc.ClientStream
}

func (x *tracertServiceLegalizeListClient) Recv() (*LegalizeListResponse, error) {
	m := new(LegalizeListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tracertServiceClient) LegalizeGet(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error) {
	out := new(Legalize)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeGetOwn(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*Certificates, error) {
	out := new(Certificates)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeGetOwn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeDone(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error) {
	out := new(Legalize)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeDone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeVerified(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*Legalize, error) {
	out := new(Legalize)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeVerified", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeRejected(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error) {
	out := new(Legalize)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeRejected", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeApproved(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*Legalize, error) {
	out := new(Legalize)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeApproved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeRating(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) LegalizeExtended(ctx context.Context, in *Legalize, opts ...grpc.CallOption) (*Legalize, error) {
	out := new(Legalize)
	err := c.cc.Invoke(ctx, "/proto.TracertService/LegalizeExtended", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) UserAnswerCreate(ctx context.Context, in *UserAnswer, opts ...grpc.CallOption) (*UserAnswer, error) {
	out := new(UserAnswer)
	err := c.cc.Invoke(ctx, "/proto.TracertService/UserAnswerCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) TracerCreate(ctx context.Context, in *Tracer, opts ...grpc.CallOption) (*Tracer, error) {
	out := new(Tracer)
	err := c.cc.Invoke(ctx, "/proto.TracertService/TracerCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) GetTrace(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*TracerList, error) {
	out := new(TracerList)
	err := c.cc.Invoke(ctx, "/proto.TracertService/GetTrace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) GetLastTrace(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*Tracer, error) {
	out := new(Tracer)
	err := c.cc.Invoke(ctx, "/proto.TracertService/GetLastTrace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracertServiceClient) GetMyAnswers(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*UserAnswerList, error) {
	out := new(UserAnswerList)
	err := c.cc.Invoke(ctx, "/proto.TracertService/GetMyAnswers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TracertServiceServer is the server API for TracertService service.
// All implementations should embed UnimplementedTracertServiceServer
// for forward compatibility
type TracertServiceServer interface {
	Login(context.Context, *LoginInput) (*User, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*StringMessage, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*StringMessage, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*StringMessage, error)
	QuestionList(context.Context, *QuestionGroupListInput) (*QuestionGroupList, error)
	AlumniRegistration(context.Context, *AlumniRegistrationInput) (*AlumniRegistrationInput, error)
	CertificateCreate(context.Context, *Certificate) (*Certificate, error)
	AlumniCreate(context.Context, *Alumni) (*Alumni, error)
	AlumniList(*ListInput, TracertService_AlumniListServer) error
	AlumniGet(context.Context, *Alumni) (*Alumni, error)
	AlumniAppraiserCreate(context.Context, *AlumniAppraiser) (*AlumniAppraiser, error)
	AlumniAppraiserList(*ListInput, TracertService_AlumniAppraiserListServer) error
	AlumniAppraiserGet(context.Context, *AlumniAppraiser) (*AlumniAppraiser, error)
	// rpc AlumniAppraiserUpdate(AlumniAppraiser) returns (AlumniAppraiser) {}
	UserCreate(context.Context, *User) (*User, error)
	UserList(*ListInput, TracertService_UserListServer) error
	UserGet(context.Context, *User) (*User, error)
	LegalizeCheck(context.Context, *StringMessage) (*Legalize, error)
	LegalizeUpload(context.Context, *Legalize) (*Legalize, error)
	LegalizeList(*ListInput, TracertService_LegalizeListServer) error
	LegalizeGet(context.Context, *Legalize) (*Legalize, error)
	LegalizeGetOwn(context.Context, *EmptyMessage) (*Certificates, error)
	LegalizeDone(context.Context, *Legalize) (*Legalize, error)
	LegalizeVerified(context.Context, *StringMessage) (*Legalize, error)
	LegalizeRejected(context.Context, *Legalize) (*Legalize, error)
	LegalizeApproved(context.Context, *StringMessage) (*Legalize, error)
	LegalizeRating(context.Context, *Legalize) (*StringMessage, error)
	LegalizeExtended(context.Context, *Legalize) (*Legalize, error)
	UserAnswerCreate(context.Context, *UserAnswer) (*UserAnswer, error)
	TracerCreate(context.Context, *Tracer) (*Tracer, error)
	GetTrace(context.Context, *EmptyMessage) (*TracerList, error)
	GetLastTrace(context.Context, *EmptyMessage) (*Tracer, error)
	GetMyAnswers(context.Context, *EmptyMessage) (*UserAnswerList, error)
}

// UnimplementedTracertServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTracertServiceServer struct {
}

func (UnimplementedTracertServiceServer) Login(context.Context, *LoginInput) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedTracertServiceServer) ForgotPassword(context.Context, *ForgotPasswordRequest) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (UnimplementedTracertServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedTracertServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedTracertServiceServer) QuestionList(context.Context, *QuestionGroupListInput) (*QuestionGroupList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuestionList not implemented")
}
func (UnimplementedTracertServiceServer) AlumniRegistration(context.Context, *AlumniRegistrationInput) (*AlumniRegistrationInput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlumniRegistration not implemented")
}
func (UnimplementedTracertServiceServer) CertificateCreate(context.Context, *Certificate) (*Certificate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CertificateCreate not implemented")
}
func (UnimplementedTracertServiceServer) AlumniCreate(context.Context, *Alumni) (*Alumni, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlumniCreate not implemented")
}
func (UnimplementedTracertServiceServer) AlumniList(*ListInput, TracertService_AlumniListServer) error {
	return status.Errorf(codes.Unimplemented, "method AlumniList not implemented")
}
func (UnimplementedTracertServiceServer) AlumniGet(context.Context, *Alumni) (*Alumni, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlumniGet not implemented")
}
func (UnimplementedTracertServiceServer) AlumniAppraiserCreate(context.Context, *AlumniAppraiser) (*AlumniAppraiser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlumniAppraiserCreate not implemented")
}
func (UnimplementedTracertServiceServer) AlumniAppraiserList(*ListInput, TracertService_AlumniAppraiserListServer) error {
	return status.Errorf(codes.Unimplemented, "method AlumniAppraiserList not implemented")
}
func (UnimplementedTracertServiceServer) AlumniAppraiserGet(context.Context, *AlumniAppraiser) (*AlumniAppraiser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlumniAppraiserGet not implemented")
}
func (UnimplementedTracertServiceServer) UserCreate(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCreate not implemented")
}
func (UnimplementedTracertServiceServer) UserList(*ListInput, TracertService_UserListServer) error {
	return status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedTracertServiceServer) UserGet(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGet not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeCheck(context.Context, *StringMessage) (*Legalize, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeCheck not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeUpload(context.Context, *Legalize) (*Legalize, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeUpload not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeList(*ListInput, TracertService_LegalizeListServer) error {
	return status.Errorf(codes.Unimplemented, "method LegalizeList not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeGet(context.Context, *Legalize) (*Legalize, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeGet not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeGetOwn(context.Context, *EmptyMessage) (*Certificates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeGetOwn not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeDone(context.Context, *Legalize) (*Legalize, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeDone not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeVerified(context.Context, *StringMessage) (*Legalize, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeVerified not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeRejected(context.Context, *Legalize) (*Legalize, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeRejected not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeApproved(context.Context, *StringMessage) (*Legalize, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeApproved not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeRating(context.Context, *Legalize) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeRating not implemented")
}
func (UnimplementedTracertServiceServer) LegalizeExtended(context.Context, *Legalize) (*Legalize, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalizeExtended not implemented")
}
func (UnimplementedTracertServiceServer) UserAnswerCreate(context.Context, *UserAnswer) (*UserAnswer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAnswerCreate not implemented")
}
func (UnimplementedTracertServiceServer) TracerCreate(context.Context, *Tracer) (*Tracer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TracerCreate not implemented")
}
func (UnimplementedTracertServiceServer) GetTrace(context.Context, *EmptyMessage) (*TracerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrace not implemented")
}
func (UnimplementedTracertServiceServer) GetLastTrace(context.Context, *EmptyMessage) (*Tracer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastTrace not implemented")
}
func (UnimplementedTracertServiceServer) GetMyAnswers(context.Context, *EmptyMessage) (*UserAnswerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyAnswers not implemented")
}

// UnsafeTracertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TracertServiceServer will
// result in compilation errors.
type UnsafeTracertServiceServer interface {
	mustEmbedUnimplementedTracertServiceServer()
}

func RegisterTracertServiceServer(s grpc.ServiceRegistrar, srv TracertServiceServer) {
	s.RegisterService(&TracertService_ServiceDesc, srv)
}

func _TracertService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).Login(ctx, req.(*LoginInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_QuestionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionGroupListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).QuestionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/QuestionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).QuestionList(ctx, req.(*QuestionGroupListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_AlumniRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlumniRegistrationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).AlumniRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/AlumniRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).AlumniRegistration(ctx, req.(*AlumniRegistrationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_CertificateCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Certificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).CertificateCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/CertificateCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).CertificateCreate(ctx, req.(*Certificate))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_AlumniCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alumni)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).AlumniCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/AlumniCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).AlumniCreate(ctx, req.(*Alumni))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_AlumniList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TracertServiceServer).AlumniList(m, &tracertServiceAlumniListServer{stream})
}

type TracertService_AlumniListServer interface {
	Send(*AlumniListResponse) error
	grpc.ServerStream
}

type tracertServiceAlumniListServer struct {
	grpc.ServerStream
}

func (x *tracertServiceAlumniListServer) Send(m *AlumniListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TracertService_AlumniGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alumni)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).AlumniGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/AlumniGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).AlumniGet(ctx, req.(*Alumni))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_AlumniAppraiserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlumniAppraiser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).AlumniAppraiserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/AlumniAppraiserCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).AlumniAppraiserCreate(ctx, req.(*AlumniAppraiser))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_AlumniAppraiserList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TracertServiceServer).AlumniAppraiserList(m, &tracertServiceAlumniAppraiserListServer{stream})
}

type TracertService_AlumniAppraiserListServer interface {
	Send(*AlumniAppraiserListResponse) error
	grpc.ServerStream
}

type tracertServiceAlumniAppraiserListServer struct {
	grpc.ServerStream
}

func (x *tracertServiceAlumniAppraiserListServer) Send(m *AlumniAppraiserListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TracertService_AlumniAppraiserGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlumniAppraiser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).AlumniAppraiserGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/AlumniAppraiserGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).AlumniAppraiserGet(ctx, req.(*AlumniAppraiser))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_UserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).UserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/UserCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).UserCreate(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_UserList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TracertServiceServer).UserList(m, &tracertServiceUserListServer{stream})
}

type TracertService_UserListServer interface {
	Send(*UserListResponse) error
	grpc.ServerStream
}

type tracertServiceUserListServer struct {
	grpc.ServerStream
}

func (x *tracertServiceUserListServer) Send(m *UserListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TracertService_UserGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).UserGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/UserGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).UserGet(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeCheck(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Legalize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeUpload(ctx, req.(*Legalize))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TracertServiceServer).LegalizeList(m, &tracertServiceLegalizeListServer{stream})
}

type TracertService_LegalizeListServer interface {
	Send(*LegalizeListResponse) error
	grpc.ServerStream
}

type tracertServiceLegalizeListServer struct {
	grpc.ServerStream
}

func (x *tracertServiceLegalizeListServer) Send(m *LegalizeListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TracertService_LegalizeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Legalize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeGet(ctx, req.(*Legalize))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeGetOwn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeGetOwn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeGetOwn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeGetOwn(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Legalize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeDone(ctx, req.(*Legalize))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeVerified_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeVerified(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeVerified",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeVerified(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeRejected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Legalize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeRejected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeRejected",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeRejected(ctx, req.(*Legalize))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeApproved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeApproved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeApproved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeApproved(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Legalize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeRating(ctx, req.(*Legalize))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_LegalizeExtended_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Legalize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).LegalizeExtended(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/LegalizeExtended",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).LegalizeExtended(ctx, req.(*Legalize))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_UserAnswerCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAnswer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).UserAnswerCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/UserAnswerCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).UserAnswerCreate(ctx, req.(*UserAnswer))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_TracerCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tracer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).TracerCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/TracerCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).TracerCreate(ctx, req.(*Tracer))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_GetTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).GetTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/GetTrace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).GetTrace(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_GetLastTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).GetLastTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/GetLastTrace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).GetLastTrace(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracertService_GetMyAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracertServiceServer).GetMyAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TracertService/GetMyAnswers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracertServiceServer).GetMyAnswers(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// TracertService_ServiceDesc is the grpc.ServiceDesc for TracertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TracertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TracertService",
	HandlerType: (*TracertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _TracertService_Login_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _TracertService_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _TracertService_ResetPassword_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _TracertService_ChangePassword_Handler,
		},
		{
			MethodName: "QuestionList",
			Handler:    _TracertService_QuestionList_Handler,
		},
		{
			MethodName: "AlumniRegistration",
			Handler:    _TracertService_AlumniRegistration_Handler,
		},
		{
			MethodName: "CertificateCreate",
			Handler:    _TracertService_CertificateCreate_Handler,
		},
		{
			MethodName: "AlumniCreate",
			Handler:    _TracertService_AlumniCreate_Handler,
		},
		{
			MethodName: "AlumniGet",
			Handler:    _TracertService_AlumniGet_Handler,
		},
		{
			MethodName: "AlumniAppraiserCreate",
			Handler:    _TracertService_AlumniAppraiserCreate_Handler,
		},
		{
			MethodName: "AlumniAppraiserGet",
			Handler:    _TracertService_AlumniAppraiserGet_Handler,
		},
		{
			MethodName: "UserCreate",
			Handler:    _TracertService_UserCreate_Handler,
		},
		{
			MethodName: "UserGet",
			Handler:    _TracertService_UserGet_Handler,
		},
		{
			MethodName: "LegalizeCheck",
			Handler:    _TracertService_LegalizeCheck_Handler,
		},
		{
			MethodName: "LegalizeUpload",
			Handler:    _TracertService_LegalizeUpload_Handler,
		},
		{
			MethodName: "LegalizeGet",
			Handler:    _TracertService_LegalizeGet_Handler,
		},
		{
			MethodName: "LegalizeGetOwn",
			Handler:    _TracertService_LegalizeGetOwn_Handler,
		},
		{
			MethodName: "LegalizeDone",
			Handler:    _TracertService_LegalizeDone_Handler,
		},
		{
			MethodName: "LegalizeVerified",
			Handler:    _TracertService_LegalizeVerified_Handler,
		},
		{
			MethodName: "LegalizeRejected",
			Handler:    _TracertService_LegalizeRejected_Handler,
		},
		{
			MethodName: "LegalizeApproved",
			Handler:    _TracertService_LegalizeApproved_Handler,
		},
		{
			MethodName: "LegalizeRating",
			Handler:    _TracertService_LegalizeRating_Handler,
		},
		{
			MethodName: "LegalizeExtended",
			Handler:    _TracertService_LegalizeExtended_Handler,
		},
		{
			MethodName: "UserAnswerCreate",
			Handler:    _TracertService_UserAnswerCreate_Handler,
		},
		{
			MethodName: "TracerCreate",
			Handler:    _TracertService_TracerCreate_Handler,
		},
		{
			MethodName: "GetTrace",
			Handler:    _TracertService_GetTrace_Handler,
		},
		{
			MethodName: "GetLastTrace",
			Handler:    _TracertService_GetLastTrace_Handler,
		},
		{
			MethodName: "GetMyAnswers",
			Handler:    _TracertService_GetMyAnswers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AlumniList",
			Handler:       _TracertService_AlumniList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AlumniAppraiserList",
			Handler:       _TracertService_AlumniAppraiserList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UserList",
			Handler:       _TracertService_UserList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LegalizeList",
			Handler:       _TracertService_LegalizeList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tracert_service.proto",
}
